// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB6K-zeWcr66CZJPXaCP550pUf6lv7SboA',
    appId: '1:102150542783:web:7eddf77d833cf3daedbd0a',
    messagingSenderId: '102150542783',
    projectId: 'msg-a7a9d',
    authDomain: 'msg-a7a9d.firebaseapp.com',
    storageBucket: 'msg-a7a9d.firebasestorage.app',
    measurementId: 'G-ZXCYCRFBD0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCQt6Xxdgf0CDaTQyBi0-OBWVfb2QDoooo',
    appId: '1:102150542783:android:a2109fe65880191dedbd0a',
    messagingSenderId: '102150542783',
    projectId: 'msg-a7a9d',
    storageBucket: 'msg-a7a9d.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB6K-zeWcr66CZJPXaCP550pUf6lv7SboA',
    appId: '1:102150542783:web:3c985923ef442a48edbd0a',
    messagingSenderId: '102150542783',
    projectId: 'msg-a7a9d',
    authDomain: 'msg-a7a9d.firebaseapp.com',
    storageBucket: 'msg-a7a9d.firebasestorage.app',
    measurementId: 'G-D870KNHYC0',
  );

}